[project]
name = "astrbot-bilibili-livemonitor"
version = "1.3"
description = "bilibili开播下播提醒Evolved"
authors = [
    { name = "Dayanshifu" },
    { name = "Nanboom233" }
]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.3",
    "astrbot>=4.14.6",
]
